qcacld-3.0: Mark wlan_hdd_state_ctrl_param functions as __maybe_unused
When building the qcacld-3.0 driver inline (MODULE not defined), the
functions wlan_hdd_state_ctrl_param_create() and
wlan_hdd_state_ctrl_param_destroy() are defined but not used, causing
a compilation error with -Werror,-Wunused-function:

  error: unused function 'wlan_hdd_state_ctrl_param_create'
        [-Werror,-Wunused-function]

These functions are only called from hdd_module_init() when MODULE is
defined and FEATURE_WLAN_RESIDENT_DRIVER is not defined. In inline
builds, they serve no purpose as the module initialization path is
different.

Mark both functions with __maybe_unused to suppress the warning and
allow the driver to be built in different configurations without
conditional compilation changes.

Signed-off-by: Santhanabalan <santhanabalan.v@hpe.com>